# Generated by Django 5.2.1 on 2025-05-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='last_update',
            field=models.DateTimeField(),
        ),
    ]
