# Generated by Django 5.2.1 on 2025-05-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_note_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
